// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type GetUserResponse = {
  user: GetUserUserResponse;
};

export type GetUserUserResponse = {
  userId: string;
  name: string;
  createdAt: string;
};

/**
 * RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:
 * ```app.UseFastEndpoints(c =&gt; c.Errors.UseProblemDetails())```
 */
export type ProblemDetails = {
  type?: null | string;
  title?: null | string;
  status?: number;
  instance?: string;
  traceId?: string;
  /**
   * the details of the error
   */
  detail?: null | string;
  errors?: Array<{
    /**
     * the name of the error or property of the dto that caused the error
     */
    name?: string;
    /**
     * the reason for the error
     */
    reason?: string;
    /**
     * the code of the error
     */
    code?: null | string;
    /**
     * the severity of the error
     */
    severity?: null | string;
  }>;
};

export type GetUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/profile";
};

export type GetUserErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Server Error
   */
  500: ProblemDetails;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
  /**
   * Success
   */
  200: GetUserResponse;
};

export type GetUserResponse2 = GetUserResponses[keyof GetUserResponses];
