// This file is auto-generated by @hey-api/openapi-ts
import { queryOptions } from "@tanstack/react-query";
import { client } from "../client.gen";
import { type Options, getUser } from "../sdk.gen";
import type { GetUserData, GetUserError, GetUserResponse2 } from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getUserQueryKey = (options?: Options<GetUserData>) =>
  createQueryKey("getUser", options);

export const getUserOptions = (options?: Options<GetUserData>) =>
  queryOptions<
    GetUserResponse2,
    GetUserError,
    GetUserResponse2,
    ReturnType<typeof getUserQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUserQueryKey(options),
  });
